### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by meyskens** [jetstack/cert-manager-olm#16]
Due to https://github.com/jetstack/cert-manager/issues/3121 we cannot release the OLM version of cert-manager 0.16 until the Helm operator has the patched JSON patch in it.

**Comment by meyskens** [comment]
Helm 3.3.1 is out! We should also release v1.0 on OLM. This should also include a test of how the upgrade behaves given big CRD changes happened

**Comment by meyskens** [comment]
Depending on https://github.com/operator-framework/operator-sdk/pull/3936

**Comment by davidkarlsen** [comment]
@meyskens the operator-sdk issue has been fixed.

**Comment by davidkarlsen** [comment]
This seems to have been merged - but I still don't see the updated version available in the operator-hub console?

**Comment by meyskens** [comment]
@davidcollom Jake is working on this, we need to change our release as the RedHat operator hub distribution format changed

**Comment by meyskens** [comment]
@ davidkarlsen sorry, autocomplete

**Comment by rursprung** [comment]
we only found v0.15.3 of the operator in the marketplace and nothing newer.
furthermore, the operator can't be found on the public openshift operator page and the link on your page is dead (see also cert-manager/website#486).
is there something missing? based on this & #20 i'd have presumed that there's a 1.x version of the operator available?
