### ISSUE TITLE
Release on OperatorHub

### ISSUE THREAD

**Issue by LorbusChris** [jetstack/cert-manager-olm#21]
I came across https://cert-manager.io/docs/installation/openshift/#installing-with-cert-manager-operator which links to a non-existent page. So I searched and found this repo :)

It seems the operator isn't yet available on OperatorHub (a now very outdated version was added to the `dev` branch last year: https://github.com/operator-framework/community-operators/tree/dev/upstream-community-operators/cert-manager).

Since this repo also hasn't been updated in a while, I'm wondering whether there still is a plan to release on OperatorHub at all?

In the OperatorHub Registry repo (https://github.com/operator-framework/community-operators) there are two catalogs:
`community-operators` for OpenShift (and its community variant OKD), as well as
`upstream-community-operators` for upstream Kubernetes.

It would be great if this operator could be added to both of these :) I'm happy to help with it, too!

**Comment by wallrj** [comment]
Hey @LorbusChris thanks for raising this issue and apologies for the slow response.

If you have time, please review #26  where I'm attempting to package cert-manager for OperatorHub, targeting both Kubernetes and OpenShift

**Comment by wallrj** [comment]
xref: 
* https://github.com/cert-manager/website/pull/626 
* https://github.com/operator-framework/community-operators/pull/4103 
* https://github.com/operator-framework/community-operators/pull/4128
* https://github.com/operator-framework/operator-lifecycle-manager/issues/1805

**Comment by LorbusChris** [comment]
Looks like I'm a bit late to the party :) Thanks for seeing this through @wallrj!

**Comment by wallrj** [comment]
Hey @LorbusChris . We merged it, but there's still quite a lot of work to do. 

I want to get all the CRDs properly documented on https://operatorhub.io/operator/cert-manager 
I was suprised that those previews don't default to the names of the CRD with the CRD descriptions.

That's how it seems to work in the OperatorHub web console on OpenShift .

**Comment by LorbusChris** [comment]
> I want to get all the CRDs properly documented on https://operatorhub.io/operator/cert-manager
> I was suprised that those previews don't default to the names of the CRD with the CRD descriptions.

Right, such a default would make sense to me. Would you mind filing an issue on https://github.com/operator-framework/community-operators/issues?

**Comment by wallrj** [comment]
Done. https://github.com/operator-framework/community-operators/issues/4179
